/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/dog.glb -t -o src/components/3d/Dog.tsx --force 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'standing' | 'sitting' | 'shake' | 'rollover' | 'play_dead'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    shiba_inu2: THREE.SkinnedMesh
    root4: THREE.Bone
  }
  materials: {
    [key: string]: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations, materials: gltfMaterials } = useGLTF('/dog.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  
  // Combine materials from GLTF and useGraph to be safe
  const targetMaterial = materials.material_0 || materials.Material_0 || gltfMaterials?.material_0 || gltfMaterials?.Material_0 || nodes.shiba_inu2.material as THREE.MeshStandardMaterial;

  React.useEffect(() => {
    if (actions['standing']) {
      actions['standing'].reset().fadeIn(0.5).play()
    } else if (animations.length > 0) {
      actions[animations[0].name]?.reset().fadeIn(0.5).play()
    }
  }, [actions, animations])

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode0" scale={0.01}>
          <group name="geo1">
            <skinnedMesh 
              name="shiba_inu2" 
              geometry={nodes.shiba_inu2.geometry} 
              skeleton={nodes.shiba_inu2.skeleton}
            >
              <meshStandardMaterial 
                map={targetMaterial?.map || null}
                color={targetMaterial?.map ? "#ffffff" : "#d89e65"}
                roughness={0.7}
                metalness={0.1}
              />
            </skinnedMesh>
          </group>
          <group name="skeletal3">
            <primitive object={nodes.root4} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dog.glb')
