/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/dog.glb -t -o src/components/3d/Dog.tsx --force 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'standing' | 'sitting' | 'shake' | 'rollover' | 'play_dead'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    shiba_inu2: THREE.SkinnedMesh
    root4: THREE.Bone
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: any) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/dog.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  
  React.useEffect(() => {
    if (actions['standing']) {
      actions['standing'].reset().fadeIn(0.5).play()
    } else if (animations.length > 0) {
      actions[animations[0].name]?.reset().fadeIn(0.5).play()
    }
  }, [actions, animations])

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode0" scale={0.01}>
          <group name="geo1">
            <skinnedMesh name="shiba_inu2" geometry={nodes.shiba_inu2.geometry} material={nodes.shiba_inu2.material} skeleton={nodes.shiba_inu2.skeleton} />
          </group>
          <group name="skeletal3">
            <primitive object={nodes.root4} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dog.glb')
