/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shiba_dog.glb -t -o src/components/3d/ShibaDog.tsx --force 
Author: quander (https://sketchfab.com/quander)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-dog-shiba-inu-9abfce885a834399b2c3ccaed51cd474
Title: Animated Dog, Shiba Inu
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = '0|play_dead_0' | '0|rollover_0' | '0|shake_0' | '0|sitting_0' | '0|standing_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_206: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/shiba_dog.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="d2a6bc8fe88e4cbca4db3d181738fe46fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Light" position={[407.625, 590.386, -100.545]} rotation={[1.89, 0.881, -2.045]} scale={100}>
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group name="Camera" position={[735.889, 495.831, 692.579]} rotation={[Math.PI, 0.756, 2.68]} scale={100}>
                  <group name="Object_8" />
                </group>
                <group name="RootNode0">
                  <group name="geo1" />
                  <group name="skeletal3">
                    <group name="0">
                      <group name="Object_13">
                        <primitive object={nodes._rootJoint} />
                        <group name="Object_205" />
                        <skinnedMesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.Material_0} skeleton={nodes.Object_206.skeleton} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="shiba_inu2" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shiba_dog.glb')
